### ISSUE TITLE
create identity

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#234]
How to create an identity with our private key?

**Comment by rauljareno** [comment]
you can create an identity with the following example:

```
PrivateIdentityEntity identity =
          await _polygonIdSdk.identity.addIdentity(privateKey);
```

**Comment by bibash28** [comment]
How to extract a private key in the future with the same secret? @rauljareno

**Comment by rauljareno** [comment]
we dont allow it if the identity is already created and stored in the sdk for security reasons. Integrator needs to store the identity private key generated in a secured way to interact with the sdk
