### ISSUE TITLE
How to extract a private key in the future with the same secret? 

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#236]
Scenario: If new private key is created user need to save two private keys here....

**Comment by rauljareno** [comment]
integrator needs to save identity private key generated using secret, so identity can be restored using method restoreIdentity.

/// Restores an [IdentityEntity] from a privateKey and encrypted backup databases
  /// associated to the identity
  /// Return an identity as a [PrivateIdentityEntity].
  /// Throws [IdentityException] if an error occurs.
  ///
  /// Identity [privateKey] is the key used to access all the sensitive info from the identity
  /// and also to realize operations like generating proofs
  /// using the claims associated to the identity
  ///
  ///  The [encryptedIdentityDbs] is a map of profile nonces and
  ///  associated encrypted Identity's Databases
  ///
  /// The identity will be restored using the current env set with [PolygonIdSdk.setEnv]
  Future<PrivateIdentityEntity> restoreIdentity(
      {required String privateKey, Map<int, String>? encryptedIdentityDbs});

**Comment by rauljareno** [comment]
they dont need to save private key if the change device, identity private key will be generated again calling addIdentity with same secret obtained from mnemonics

**Comment by bibash28** [comment]
When i tried with same secret, it throws error - something like already exist...

**Comment by rauljareno** [comment]
it cannot exist if it's a new device
