### ISSUE TITLE
issuer-demo.polygonid issue

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#239]
https://issuer-demo.polygonid.me/  provides me json data.
But when I parse it with the OfferIden3MessageEntity model, I got an error.

Attempt:
```
 final offerIden3MessageEntity = OfferIden3MessageEntity.fromJson(json);
 ```

Error:
```
Error -type 'Null' is not a subtype of type 'List<dynamic>' in type cast<…>
```

Reason:
```
class OfferBodyRequest {
  ...
  factory OfferBodyRequest.fromJson(Map<String, dynamic> json) {
    List<CredentialOfferData> credentials = (json['credentials'] as List)
        .map((item) => CredentialOfferData.fromJson(item))
        .toList();
   ...
}
```

**Comment by bibash28** [comment]
i am trying to get the credential by scanning. @Plumillon

**Comment by Plumillon** [comment]
Use the String you got from scanning as param for [PolygonIdSdk.iden3comm.getIden3Message](https://github.com/iden3/polygonid-flutter-sdk/blob/develop/lib/sdk/iden3comm.dart#L25), you will have an `Iden3messageEntity`.

**Comment by bibash28** [comment]
okm thanks
