### ISSUE TITLE
Error -PathNotFoundException: Cannot open file, path =

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#241]
`Error: Error -PathNotFoundException: Cannot open file, path = '/var/mobile/Containers/Data/Application/0A46465E-1722-4F51-B7C9-35AC2C04E842/Documents/authV2.dat' (OS Error: No such file or directory, errno = 2)`
 
Tested on iOS

```
Step 1: 
got string from https://issuer-demo.polygonid.me/
```

```
Step 2:  
final iden3MessageEntity =
    await sdk.iden3comm.getIden3Message(message: string);
```

```
Step 3:
    await sdk.iden3comm.authenticate(
      message: iden3MessageEntity,
      did: did,
      privateKey: privateKey,
    );
```

```
Step 4:
await sdk.iden3comm.fetchAndSaveClaims(
      message: iden3MessageEntity,
      did: did,
      privateKey: privateKey,
    )

```

**Comment by rauljareno** [comment]
before being able to authenticate, you need to fetch the circuit files.

```
Stream<DownloadInfo> stream =
        await sdk.proof.initCircuitsDownloadAndGetInfoStream;
```

Please, follow the integration example included to know how to interact with the sdk: 
https://github.com/iden3/polygonid-flutter-sdk/tree/develop/example
