### ISSUE TITLE
RPCError: got code -32002 with msg "project ID does not have access to polygon l2"

### ISSUE THREAD

**Issue by hawkbee1** [iden3/polygonid-flutter-sdk#244]
When trying to sign up on https://issuer-demo.polygonid.me/auth-qr after creating my identity and getting my DID I get error message about project ID not having access to polygon l2.
Is this a permission issue which should be solved on issuer-demo.polygonid.me ?

![image](https://user-images.githubusercontent.com/49282360/228592769-f91e69a1-3e56-4560-b8c5-c193083489fb.png)

**Comment by Plumillon** [comment]
Salut @hawkbee1 🇫🇷 ,
Can you check you have a valid `web3RdpUrl` and `web3ApiKey` in your `.env` file?

**Comment by hawkbee1** [comment]
Merci @Plumillon fr , I understand the issue now and I enabled the https://polygon-mumbai.infura.io/v3/ endpoint in Infura account. In fact this endpoint is the only valid one, correct?
I now have another issue on authentication but I see there is already a thread on this topic.

**Comment by Plumillon** [comment]
For the moment Infura is the only one "officially" supported, but you can test with any other provider (like Quicknode) and it should work the same!
