### ISSUE TITLE
conflict in sdk example and release polygon id

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#247]
Appstore polygon id
- `mnemonics` is linked with `identity`
- the user only has to remember `mnemonics`

In SDK example
- there is a function to use `secret` to create a `private key`
- functions are using fixed `access message` to create `private key`

While we are trying to implement
- our app already has one `mnemonics` but we need to generate a `secret` from `mnemonics`
- that `secret` again creates a `private key`
- in this case users of our app should remember both `mnemonics` and `private key`

What if there is a 
function, that accepts `mnemonics` and gives us `PrivateIdentityEntity` directly...
or 
function to create a `secret` from `mnemonics`

**Comment by rauljareno** [comment]
use the mnemonics as secret and remove the identity with private key if you need to create again the same identity with the mnemonics. You can also implement the method to derive the private key from the secret on app side checking the implementation. For security reasons this is not allowed on sdk side for now

**Comment by bibash28** [comment]
'You can also implement the method to derive the private key from the secret on the app side checking the implementation'. Can you help with this part? @rauljareno
