### ISSUE TITLE
Could not build the precompiled application for the device.

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#255]
Error (Xcode): ../../../../../.pub-cache/git/polygonid-flutter-sdk-4ea531794579669c70d08ddf724543c468fbda0c/lib/sdk/di/injector.dart:29:8: Error: Error when reading '../../../../../.pub-cache/git/polygonid-flutter-sdk-4ea531794579669c70d08ddf724543c468fbda0c/lib/sdk/di/injector.config.dart': No such file or directory

**Comment by bibash28** [comment]
generated files also need to be added. otherwise, we cannot use it as a package..

**Comment by Plumillon** [comment]
Hi @bibash28 !
Can you try to run `flutter packages pub run build_runner build` to see if it generates them?
Meanwhile, we will add them again

**Comment by Plumillon** [comment]
We just pushed again the generated files, fixed if you pull

**Comment by bibash28** [comment]
> Hi @bibash28 ! Can you try to run `flutter packages pub run build_runner build` to see if it generates them? Meanwhile, we will add them again

yes.. I was using it..
