### ISSUE TITLE
Iphone/IOS not available to test in current build

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#256]
Tested with: Iphone X and ipad pro

I tried to run `https://github.com/iden3/polygonid-flutter-sdk/tree/develop/example` with Xcode.. But devices are not available to run the app..

**Comment by rauljareno** [comment]
Set minimum deployment target to 14.0. Running using flutter in terminal or android studio. Just cloned the repository from develop branch, followed the readme instructions and successfully run the example app in debug mode on ios simulator and in release mode on real device. Closing issue.
