### ISSUE TITLE
White screen issue while implementation

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#257]
Extended version of https://github.com/iden3/polygonid-flutter-sdk/issues/245

I updated the SDK. But need instructions to update files inside the ios folder. So that I can implement it in the project.

After init is called app is freezed.

**Comment by hawkbee1** [comment]
In local release mode we were able to get this error message while having the white screen : Error: Invalid argument(s): Failed to lookup sumbol 'poseidon_hash2':dlsym(RTLD_DEFAULT, poseidon_hash2):symbol not found
specific ticket opened for this message: https://github.com/iden3/polygonid-flutter-sdk/issues/259

**Comment by rauljareno** [comment]
Set minimum deployment target to 14.0. Just cloned the repository from develop branch, followed the readme instructions and successfully run the example app in debug mode on ios simulator and in release mode on real device. Closing issue.
