### ISSUE TITLE
Failed to lookup sumbol 'poseidon_hash2':dlsym

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#259]
Release mode issue on iOS

Action: Trying to do an init call

Error: Invalid argument(s): Failed to lookup sumbol 'poseidon_hash2':dlsym(RTLD_DEFAULT, poseidon_hash2):symbol not found

This error also causes a white screen in iOS..

**Comment by rauljareno** [comment]
Set minimum deployment target to 14.0. Just cloned the repository from develop branch, followed the readme instructions and successfully run the example app in debug mode on ios simulator and in release mode on real device. Closing issue.
