### ISSUE TITLE
Failed to lookup sumbol 'poseidon_hash2':dlsym

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#260]
Release mode on iOS
Tested on iPad/iPhone

Repository to test: https://github.com/bibash28/polygon-id-test
Command: flutter run --release

Implemented as per readme instruction

Screenshot:
![IMG_2573](https://user-images.githubusercontent.com/18188709/230375771-657cfcc7-c53e-441a-b60c-fd37b765f39f.PNG)

**Comment by rauljareno** [comment]
Hi @bibash28 just tested on release mode your project and you need to do the following to fix the issue. Open Xcode xcworkspace of your project, go to Runner target -> Build Settings and set "Dead Code Stripping" value to NO.

<img width="826" alt="Screenshot 2023-04-10 at 05 17 19" src="https://user-images.githubusercontent.com/20462651/230900499-979215af-1311-44c7-9304-ab8ed1c96748.png">

**Comment by otto-mora** [comment]
Comment from Romauld:  We can't set "dead code stripping" to false. With this configuration we can't build our app because other SDKs are getting duplicate symbols. Any suggestions @rauljareno ?

**Comment by bibash28** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/18188709/231668628-93102cb5-d458-4d67-8628-8e4475352c4b.png">

**Comment by otto-mora** [comment]
Hey @bibash28 , you already followed these steps as suggested in the link:

Stripping iOS symbols:
In Xcode, go to Target Runner > Build Settings > Strip Style.
Change from All Symbols to Non-Global Symbols.

**Comment by bibash28** [comment]
Hey @otto-mora,  

No, I have not followed. Let me try.

**Comment by bibash28** [comment]
Hey @otto-mora,
Thank you , this solved the issue..

**Comment by bibash28** [comment]
Hey @otto-mora,
Sorry, I was not testing in release mode..

**Comment by otto-mora** [comment]
Hey @bibash28 did it work in the end? Can you confirm please or let us know any other errors you might be seeing?

**Comment by bibash28** [comment]
Hey @otto-mora, it is not working on our side... Same issue from start...

**Comment by rauljareno** [comment]
@bibash28 just added a fix to develop branch, could you please check again? thanks!

**Comment by bibash28** [comment]
Not solved... @rauljareno @otto-mora

**Comment by rauljareno** [comment]
@bibash28 thanks for the feedback, I added new fix to develop branch also for that symbol and the rest that might be missing, could you please check? thanks!

**Comment by bibash28** [comment]
working now. Thank you.
