### ISSUE TITLE
Backup/restore credentials

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#270]
## 2.0.0
- Did support
- Verifiable credentials
- Backup/restore credentials

The changelog contains this listing. But I could not find any function call to backup and restore credentials.

**Comment by rauljareno** [comment]
Future<String?> backupIdentity({
    required String privateKey,
  });

Future<PrivateIdentityEntity> restoreIdentity(
      {required String privateKey, String? encryptedDb});

**Comment by rauljareno** [comment]
Affer calling restoreIdentity passing as param the encryptedDb you got as response from backupIdentity, credentials are recovered in the sdk, so calling credential.getClaims method should return the claims restored.

**Comment by bibash28** [comment]
Hello @rauljareno,

Step 1:
`final encryptedDb = sdk.identity.backupIdentity(privateKey: privateKey);`

Step 2:
```
    final privateIdentityEntity = await sdk.identity.restoreIdentity(
      privateKey: privateKey,
      encryptedDb: encryptedDb,
    );
```
    
I did this step. So, what is the further process with `privateIdentityEntity`??


`getClaims` requires `Iden3MessageEntity` parameter. I don't have this with above steps. Am I missing anything?

Our moto is to `backup`, save somewhere and `restore` the credentials in the wallet..

**Comment by hawkbee1** [comment]
@rauljareno backupIdentity vale is supposed to contains encrypted credentials (claims) ?

**Comment by rauljareno** [comment]
hello @bibash28 @hawkbee1 ,

you were using `getClaims` from `iden3comm` that is for interacting with issuer/verifier messages. I was referring to `getClaims` from `credential`. So in the end it will look like this:

Step 1:
`final encryptedDb = sdk.identity.backupIdentity(privateKey: privateKey);`

Step 2:

 ```
   final privateIdentityEntity = await sdk.identity.restoreIdentity(
      privateKey: privateKey,
      encryptedDb: encryptedDb,
    );
```
Step 3: 

```
final List<ClaimEntity> credentials = await sdk.credential.getClaims(
      genesisDid: privateIdentityEntity.did,
      privateKey: privateIdentityEntity.privateKey
);
```

**Comment by bibash28** [comment]
Hello @rauljareno ,

If the user has already did and the private key saved already, then we should not have to go through steps 1 and 2. Am I right?

**Comment by rauljareno** [comment]
steps 1 and 2 are for backing up and restoring the identity and the credentials stored in the sdk. If Identity is already created in the sdk and there are credentials already stored in the sdk, you can call step 3 directly.

**Comment by rauljareno** [comment]
steps 1 and 2 are for backing up and restoring the identity and the credentials stored in the sdk. If Identity is already created in the sdk and there are credentials already stored in the sdk, you can call step 3 directly.
