### ISSUE TITLE
SDK works on old iPhones

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#285]
According to SDK limitation, only device with A12 to the latest chips supports SDK.

But I was able to run SDK on iPhone 6 and iPhone X.

**Comment by rauljareno** [comment]
Hi @bibash28 have you tested all proof generation flow? thanks

**Comment by bibash28** [comment]
Nope.
- I downloaded circuits, authenticated, and added claims. But I have not tested proof properly...

**Comment by bibash28** [comment]
Hello @rauljareno ,

This is the first step of verification,
```
{
  "id": "fe581ff0-f591-4b8a-a0c0-a499b0a597b0",
  "typ": "application/iden3comm-plain-json",
  "type": "https://iden3-communication.io/authorization/1.0/request",
  "thid": "fe581ff0-f591-4b8a-a0c0-a499b0a597b0",
  "body": {
    "callbackUrl": "https://self-hosted-demo-backend-platform.polygonid.me/api/callback?sessionId=412207",
    "reason": "test flow",
    "scope": [
      {
        "id": 1,
        "circuitId": "credentialAtomicQuerySigV2",
        "query": {
          "allowedIssuers": [
            "*"
          ],
          "context": "https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld",
          "credentialSubject": {
            "birthday": {
              "$lt": 20000101
            }
          },
          "type": "KYCAgeCredential"
        }
      }
    ]
  },
  "from": "did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5"
}
```

How are we evaluating proof type from above data?

**Comment by rauljareno** [comment]
step 1. Convert the json message to an valid object

`Future<Iden3MessageEntity> getIden3Message({required String message});`

step 2. Authenticate using the iden3message and valid credential to generate the proof

`Future<void> authenticate({
    required Iden3MessageEntity message,
    required String genesisDid,
    BigInt? profileNonce,
    required String privateKey,
    String? pushToken,
  })`

**Comment by bibash28** [comment]
Hello @rauljareno ,
I saw this screen. Is this hard-coded? Or how it is generated - `cryptographic proof`?
<img width="716" alt="image" src="https://user-images.githubusercontent.com/18188709/235092865-018cb234-8f1a-4317-aeda-d3f6d2869621.png">

**Comment by rauljareno** [comment]
this screen is created based on the iden3messageEntity object, it's simple UI

**Comment by bibash28** [comment]
Thanks for sharing.. 

But developers should know what type of object produces different results. Also, mapping also needs to be known. For example, I guess the circuit id is mapped to the signature type.

**Comment by rauljareno** [comment]
thanks for your thoughts @bibash28 Any feedback is welcomed and we will have it in mind for future releases :)

**Comment by rauljareno** [comment]
@bibash28 btw, could you share the repository where you were able to add support for old iphones? thanks

**Comment by bibash28** [comment]
Sure..

https://github.com/TalaoDAO/AltMe
