### ISSUE TITLE
How to map circuit Id with proof type?

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#286]
How do we deduce if it is BJJ, SMT etc?
<img width="716" alt="image" src="https://user-images.githubusercontent.com/18188709/235093470-6ef5dec0-6e03-4203-b4f7-85ed092de946.png">

**Comment by rauljareno** [comment]
you can use directly the proofType, we are in app side translating these proof specific proof types to natural language to follow the design requests:

`if (proof['type'] == "Iden3SparseMerkleProof" ||
            proof['type'] == "Iden3SparseMerkleTreeProof") {
          proofType += '- SMT Signature\n';
        } else if (proof['type'] == "BJJSignature2021") {
          proofType += '- BJJ Signature\n';
        } else {
          proofType += '- ${proof['type']}\n';
        }`

**Comment by bibash28** [comment]
Hello @rauljareno ,

For example if I get following json in auth
```
{
  "id": "fe581ff0-f591-4b8a-a0c0-a499b0a597b0",
  "typ": "application/iden3comm-plain-json",
  "type": "https://iden3-communication.io/authorization/1.0/request",
  "thid": "fe581ff0-f591-4b8a-a0c0-a499b0a597b0",
  "body": {
    "callbackUrl": "https://self-hosted-demo-backend-platform.polygonid.me/api/callback?sessionId=412207",
    "reason": "test flow",
    "scope": [
      {
        "id": 1,
        "circuitId": "credentialAtomicQuerySigV2",
        "query": {
          "allowedIssuers": [
            "*"
          ],
          "context": "https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld",
          "credentialSubject": {
            "birthday": {
              "$lt": 20000101
            }
          },
          "type": "KYCAgeCredential"
        }
      }
    ]
  },
  "from": "did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5"
}
```

How to get `proof['type']` in this case?

**Comment by rauljareno** [comment]
you need to search a credential that fulfills the proof request:

- context: "https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld"
- Type: "KYCAgeCredential"
- issuer: Any "*"
- birthday field lower than 20000101

for that, you need to call the following method from iden3comm:

`Future<List<ClaimEntity>> getClaims({
    required Iden3MessageEntity message,
    required String genesisDid,
    BigInt? profileNonce,
    required String privateKey,
  });`

**Comment by rauljareno** [comment]
also, from proof request, to see the link between proof type and circuitId, check this snippet of code

`if (widget.data.proofScopeRequest.circuitId ==
            "credentialAtomicQuerySigV2" ||
        widget.data.proofScopeRequest.circuitId ==
            "credentialAtomicQuerySigV2OnChain") {
      proofTypeMsg = " - BJJ Signature";
    } else if (widget.data.proofScopeRequest.circuitId ==
            "credentialAtomicQueryMTPV2" ||
        widget.data.proofScopeRequest.circuitId ==
            "credentialAtomicQueryMTPV2OnChain") {
      proofTypeMsg = " - SMT Signature";
    }`

**Comment by bibash28** [comment]
ok.. thank you..

**Comment by bibash28** [comment]
Hello @rauljareno ,

i was wondering how is text produced based on credentialSubject. We are trying to make common texts.

For e.g.

`{countyCode: {$nin:[840,120,340,509]}}`

```
- countryCode is not one of the following values:

- 840
- 120
- 340
- 509
```

**Comment by bibash28** [comment]
Also, what are the probable values of `Allowed issuers` and mapping
e.g.
* => All

**Comment by rauljareno** [comment]
@bibash28 about the countryCode question, you will need to generate a vocab file inside the credential schema to translate those values to specific strings. For doing so, please rise that question in this repository https://github.com/iden3/claim-schema-vocab.

About allowed issuers, it will accept a list of dids string of the issuers or an asterisk for any issuer.
