### ISSUE TITLE
Authentication Fails in example app

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#288]
![image](https://user-images.githubusercontent.com/18188709/235573514-a93519af-0192-4879-b5b5-da3c099d6a7b.png)

**Comment by rauljareno** [comment]
@bibash28 please, update your .env file with the following config, be aware you need to use your own infura api key for making it work.

ENV_POLYGON_MUMBAI={"blockchain": "polygon", "network": "mumbai", "web3Url": "https://polygon-mumbai.infura.io/v3/", "web3RdpUrl": "wss://polygon-mumbai.infura.io/v3/", "web3ApiKey": "YOUR_INFURA_API_KEY", "idStateContract": "0x134B1BE34911E39A8397ec6289782989729807a4", "pushUrl": "https://push-staging.polygonid.com/api/v1"}
